In [1]:
import pandas as pd

In [3]:
df = pd.read_excel("ml loan_approval_1000 data sheet.xlsx")

In [5]:
df

     Age    Income  Loan_Amount  Credit_Score Employment_Type  Loan_Approved
0     59   77761.0       417505           337        Salaried              0
1     49  141178.0       328226           487        Salaried              0
2     35   56368.0       312805           356   Self-Employed              0
3     28   26783.0       218484           319        Salaried              0
4     41  131530.0       315064           572   Self-Employed              0
..   ...       ...          ...           ...             ...            ...
995   58  112447.0       259717           572      Unemployed              0
996   22  134994.0       314167           544      Unemployed              0
997   27  109899.0       169654           749        Salaried              1
998   38   40049.0       240868           546      Unemployed              0
999   47   95717.0       130073           819        Salaried              1

[1000 rows x 6 columns]

In [8]:
df.isna().sum()

Age                 0
Income             50
Loan_Amount         0
Credit_Score        0
Employment_Type    50
Loan_Approved       0
dtype: int64

In [10]:
len(df)

1000

In [23]:
me = df["Income"].mean()
mo = df["Employment_Type"].mode()[0]

In [31]:
df["Income"] = df["Income"].fillna(me)
df["Employment_Type"] = df["Employment_Type"].fillna(mo)

In [17]:
me = df["Income"].mean()

In [28]:
mo

'Salaried'

In [33]:
df.isna().sum()

Age                0
Income             0
Loan_Amount        0
Credit_Score       0
Employment_Type    0
Loan_Approved      0
dtype: int64

In [35]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["Employment_Type"] = le.fit_transform(df["Employment_Type"])

In [36]:
df

     Age    Income  Loan_Amount  Credit_Score  Employment_Type  Loan_Approved
0     59   77761.0       417505           337                0              0
1     49  141178.0       328226           487                0              0
2     35   56368.0       312805           356                1              0
3     28   26783.0       218484           319                0              0
4     41  131530.0       315064           572                1              0
..   ...       ...          ...           ...              ...            ...
995   58  112447.0       259717           572                2              0
996   22  134994.0       314167           544                2              0
997   27  109899.0       169654           749                0              1
998   38   40049.0       240868           546                2              0
999   47   95717.0       130073           819                0              1

[1000 rows x 6 columns]

In [38]:
le.classes_

array([0, 1, 2])

In [39]:
x = df.drop("Loan_Approved", axis=1)
y = df["Loan_Approved"]

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [63]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=10000)
lr.fit(x_train, y_train)

LogisticRegression(max_iter=10000)

In [64]:
y_pred = lr.predict(x_test)

In [67]:
y_pred

array([0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1])

In [68]:
y_test

675    0
865    0
887    1
360    1
395    0
      ..
119    1
930    1
315    0
825    0
89     1
Name: Loan_Approved, Length: 200, dtype: int64

In [69]:
from sklearn.metrics import classification_report

print (classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.90      0.86       134
           1       0.75      0.59      0.66        66

    accuracy                           0.80       200
   macro avg       0.78      0.75      0.76       200
weighted avg       0.80      0.80      0.79       200